server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

url: jdbc:mysql://localhost:3306/sdpDB
username: root
password: Blue_174973
#driverClass: com.mysql.jdbc.Driver